name: flashmemo
description: 移动端智能闪记卡应用

version: 1.0.0+1

# 应用描述
publish_to: 'none' # 防止意外发布到pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.0.5
  
  # 数据库
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # 网络请求
  http: ^1.1.0
  dio: ^5.3.2
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # UI组件
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  
  # 媒体处理
  image_picker: ^1.0.4
  audioplayers: ^5.2.1
  video_player: ^2.7.2
  
  # 文件处理
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  
  # 工具库
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # 启用代码生成
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700